### ISSUE TITLE
Returns error #803 from Facebook Graph API when attempting login via Android

### ISSUE THREAD

**Issue by HadenHiles** [the-meedu-app/flutter-facebook-auth#19]
Here is the Debug Output in VS Code: 

```E/flutter (20656): #6      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:992
E/flutter (20656): #7      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:1098
E/flutter (20656): #8      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:184
E/flutter (20656): #9      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:524
E/flutter (20656): #10     BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:284
E/flutter (20656): #11     BaseTapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:219
E/flutter (20656): #12     PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:477
E/flutter (20656): #13     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:78
E/flutter (20656): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> 
package:flutter/…/gestures/pointer_router.dart:124
E/flutter (20656): #15     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (20656): #16     PointerRouter._dispatchEventToRoutes 
package:flutter/…/gestures/pointer_router.dart:122
E/flutter (20656): #17     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:108
Launching lib\main.dart on Pixel 4 XL in debug mode...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Connecting to VM Service at ws://127.0.0.1:54127/qmr1H2zvLAI=/ws
I/facebook:(20656): sasasas
W/ActivityThread(20656): handleWindowVisibility: no activity for token android.os.BinderProxy@3734622
E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
E/flutter (20656): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(500, SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: , null)
E/flutter (20656): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:572
E/flutter (20656): #1      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:161
E/flutter (20656): <asynchronous suspension>
E/flutter (20656): #2      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:334
E/flutter (20656): #3      FacebookAuth.login 
package:flutter_facebook_auth/flutter_facebook_auth.dart:32
E/flutter (20656): #4      signInWithFacebook 
package:thepondapp/SignIn.dart:26
E/flutter (20656): #5      Login.build.<anonymous closure> 
package:thepondapp/Login.dart:42
E/flutter (20656): #18     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:220
E/flutter (20656): #19     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
E/flutter (20656): #20     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:158
E/flutter (20656): #21     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:104
E/flutter (20656): #22     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:88
E/flutter (20656): #23     _rootRunUnary  (dart:async/zone.dart:1206:13)
E/flutter (20656): #24     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (20656): #25     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
E/flutter (20656): #26     _invoke1  (dart:ui/hooks.dart:267:10)
E/flutter (20656): #27     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)
E/flutter (20656):
E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
```

**Comment by the-meedu-app** [comment]
> Here is the Debug Output in VS Code:
> 
> ```
> package:flutter/…/material/ink_well.dart:992
> E/flutter (20656): #7      _InkResponseState.build.<anonymous closure> 
> package:flutter/…/material/ink_well.dart:1098
> E/flutter (20656): #8      GestureRecognizer.invokeCallback 
> package:flutter/…/gestures/recognizer.dart:184
> E/flutter (20656): #9      TapGestureRecognizer.handleTapUp 
> package:flutter/…/gestures/tap.dart:524
> E/flutter (20656): #10     BaseTapGestureRecognizer._checkUp 
> package:flutter/…/gestures/tap.dart:284
> E/flutter (20656): #11     BaseTapGestureRecognizer.handlePrimaryPointer 
> package:flutter/…/gestures/tap.dart:219
> E/flutter (20656): #12     PrimaryPointerGestureRecognizer.handleEvent 
> package:flutter/…/gestures/recognizer.dart:477
> E/flutter (20656): #13     PointerRouter._dispatch 
> package:flutter/…/gestures/pointer_router.dart:78
> E/flutter (20656): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> 
> package:flutter/…/gestures/pointer_router.dart:124
> E/flutter (20656): #15     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
> E/flutter (20656): #16     PointerRouter._dispatchEventToRoutes 
> package:flutter/…/gestures/pointer_router.dart:122
> E/flutter (20656): #17     PointerRouter.route 
> package:flutter/…/gestures/pointer_router.dart:108
> Launching lib\main.dart on Pixel 4 XL in debug mode...
> ✓ Built build\app\outputs\flutter-apk\app-debug.apk.
> Installing build\app\outputs\flutter-apk\app.apk...
> Connecting to VM Service at ws://127.0.0.1:54127/qmr1H2zvLAI=/ws
> I/facebook:(20656): sasasas
> W/ActivityThread(20656): handleWindowVisibility: no activity for token android.os.BinderProxy@3734622
> E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> E/flutter (20656): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(500, SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: , null)
> E/flutter (20656): #0      StandardMethodCodec.decodeEnvelope 
> package:flutter/…/services/message_codecs.dart:572
> E/flutter (20656): #1      MethodChannel._invokeMethod 
> package:flutter/…/services/platform_channel.dart:161
> E/flutter (20656): <asynchronous suspension>
> E/flutter (20656): #2      MethodChannel.invokeMethod 
> package:flutter/…/services/platform_channel.dart:334
> E/flutter (20656): #3      FacebookAuth.login 
> package:flutter_facebook_auth/flutter_facebook_auth.dart:32
> E/flutter (20656): #4      signInWithFacebook 
> package:thepondapp/SignIn.dart:26
> E/flutter (20656): #5      Login.build.<anonymous closure> 
> package:thepondapp/Login.dart:42
> E/flutter (20656): #18     GestureBinding.handleEvent 
> package:flutter/…/gestures/binding.dart:220
> E/flutter (20656): #19     GestureBinding.dispatchEvent 
> package:flutter/…/gestures/binding.dart:200
> E/flutter (20656): #20     GestureBinding._handlePointerEvent 
> package:flutter/…/gestures/binding.dart:158
> E/flutter (20656): #21     GestureBinding._flushPointerEventQueue 
> package:flutter/…/gestures/binding.dart:104
> E/flutter (20656): #22     GestureBinding._handlePointerDataPacket 
> package:flutter/…/gestures/binding.dart:88
> E/flutter (20656): #23     _rootRunUnary  (dart:async/zone.dart:1206:13)
> E/flutter (20656): #24     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
> E/flutter (20656): #25     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
> E/flutter (20656): #26     _invoke1  (dart:ui/hooks.dart:267:10)
> E/flutter (20656): #27     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)
> E/flutter (20656):
> E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> ```

Please provide your code to help you

**Comment by the-meedu-app** [comment]
> > Here is the Debug Output in VS Code:
> > ```
> > package:flutter/…/material/ink_well.dart:992
> > E/flutter (20656): #7      _InkResponseState.build.<anonymous closure> 
> > package:flutter/…/material/ink_well.dart:1098
> > E/flutter (20656): #8      GestureRecognizer.invokeCallback 
> > package:flutter/…/gestures/recognizer.dart:184
> > E/flutter (20656): #9      TapGestureRecognizer.handleTapUp 
> > package:flutter/…/gestures/tap.dart:524
> > E/flutter (20656): #10     BaseTapGestureRecognizer._checkUp 
> > package:flutter/…/gestures/tap.dart:284
> > E/flutter (20656): #11     BaseTapGestureRecognizer.handlePrimaryPointer 
> > package:flutter/…/gestures/tap.dart:219
> > E/flutter (20656): #12     PrimaryPointerGestureRecognizer.handleEvent 
> > package:flutter/…/gestures/recognizer.dart:477
> > E/flutter (20656): #13     PointerRouter._dispatch 
> > package:flutter/…/gestures/pointer_router.dart:78
> > E/flutter (20656): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> 
> > package:flutter/…/gestures/pointer_router.dart:124
> > E/flutter (20656): #15     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
> > E/flutter (20656): #16     PointerRouter._dispatchEventToRoutes 
> > package:flutter/…/gestures/pointer_router.dart:122
> > E/flutter (20656): #17     PointerRouter.route 
> > package:flutter/…/gestures/pointer_router.dart:108
> > Launching lib\main.dart on Pixel 4 XL in debug mode...
> > ✓ Built build\app\outputs\flutter-apk\app-debug.apk.
> > Installing build\app\outputs\flutter-apk\app.apk...
> > Connecting to VM Service at ws://127.0.0.1:54127/qmr1H2zvLAI=/ws
> > I/facebook:(20656): sasasas
> > W/ActivityThread(20656): handleWindowVisibility: no activity for token android.os.BinderProxy@3734622
> > E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> > E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> > E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> > E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> > E/flutter (20656): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(500, SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: , null)
> > E/flutter (20656): #0      StandardMethodCodec.decodeEnvelope 
> > package:flutter/…/services/message_codecs.dart:572
> > E/flutter (20656): #1      MethodChannel._invokeMethod 
> > package:flutter/…/services/platform_channel.dart:161
> > E/flutter (20656): <asynchronous suspension>
> > E/flutter (20656): #2      MethodChannel.invokeMethod 
> > package:flutter/…/services/platform_channel.dart:334
> > E/flutter (20656): #3      FacebookAuth.login 
> > package:flutter_facebook_auth/flutter_facebook_auth.dart:32
> > E/flutter (20656): #4      signInWithFacebook 
> > package:thepondapp/SignIn.dart:26
> > E/flutter (20656): #5      Login.build.<anonymous closure> 
> > package:thepondapp/Login.dart:42
> > E/flutter (20656): #18     GestureBinding.handleEvent 
> > package:flutter/…/gestures/binding.dart:220
> > E/flutter (20656): #19     GestureBinding.dispatchEvent 
> > package:flutter/…/gestures/binding.dart:200
> > E/flutter (20656): #20     GestureBinding._handlePointerEvent 
> > package:flutter/…/gestures/binding.dart:158
> > E/flutter (20656): #21     GestureBinding._flushPointerEventQueue 
> > package:flutter/…/gestures/binding.dart:104
> > E/flutter (20656): #22     GestureBinding._handlePointerDataPacket 
> > package:flutter/…/gestures/binding.dart:88
> > E/flutter (20656): #23     _rootRunUnary  (dart:async/zone.dart:1206:13)
> > E/flutter (20656): #24     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
> > E/flutter (20656): #25     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
> > E/flutter (20656): #26     _invoke1  (dart:ui/hooks.dart:267:10)
> > E/flutter (20656): #27     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)
> > E/flutter (20656):
> > E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> > E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> > E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> > E/GraphResponse(20656): {HttpStatus: 404, errorCode: 803, subErrorCode: -1, errorType: OAuthException, errorMessage: (#803) Cannot query users by their username (CHANGE-ME)}
> > ```
> 
> Please provide your code to help you

Also make sure that you has been configured the  facebook sdk on Android https://github.com/the-meedu-app/flutter-facebook-auth#install-on-android

**Comment by HadenHiles** [comment]
pubspec.yaml:

```yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.5.0"
  firebase_auth: "^0.18.0+1"
  flutter_facebook_auth: "^0.2.3"
```

AndroidManifest.xml in /Android/app/src/main:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.howtohockey.thepondapp">
	<!--
	io.flutter.app.FlutterApplication is an android.app.Application that
	calls FlutterMain.startInitialization(this); in its onCreate method.
	In most cases you can leave this as-is, but you if you want to provide
	additional functionality it is fine to subclass or reimplement
	FlutterApplication and put your custom class here.
	-->
	<application android:name="io.flutter.app.FlutterApplication" android:label="thepondapp" android:icon="@mipmap/ic_launcher">
		<activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
			<!--
			Specifies an Android theme to apply to this Activity as soon as
			the Android process has started. This theme is visible to the user
			while the Flutter UI initializes. After that, this theme continues
			to determine the Window background behind the Flutter UI.
			-->
			<meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
			<!--
			Displays an Android View that continues showing the launch screen
			Drawable until Flutter paints its first frame, then this splash
			screen fades out. A splash screen is useful to avoid any visual
			gap between the end of Android's launch screen and the painting of
			Flutter's first frame.
			-->
			<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<!--
		Don't delete the meta-data below.
		This is used by the Flutter tool to generate GeneratedPluginRegistrant.java
		-->
		<meta-data android:name="flutterEmbedding" android:value="2" />
		<activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/app_name" />
	</application>

	<uses-permission android:name="android.permission.INTERNET"/>
</manifest>
```
I don't believe I have to set the Facebook App Id in the manifest or strings.xml file because firebase_auth takes care of that for me (I have the app id and secret set correctly within Firebase authentication and the Oauth redirect uri is configured in the facebook app as well).

Here is where I actually make the call to FacebookAuth.instance.login() in my SignIn.dart
```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';

final FirebaseAuth _auth = FirebaseAuth.instance;

Future<UserCredential> signInWithFacebook() async {
  // Trigger the sign-in flow
  final LoginResult result = await FacebookAuth.instance.login();

  // Create a credential from the access token
  final FacebookAuthCredential facebookAuthCredential =
      FacebookAuthProvider.credential(result.accessToken.token);

  // Once signed in, return the UserCredential
  return await _auth.signInWithCredential(facebookAuthCredential);
}
```
Called with the following flutter_signin_button:
```dart
SignInButton(
  Buttons.Facebook,
  onPressed: () {
    signInWithFacebook().then((credential) {
      if (credential.user != null) {
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(
            builder: (context) {
              return Dashboard();
            },
          ),
        );
      }
    });
  },
),
```

Thanks for getting back to me, any help is much appreciated 👍

**Comment by HadenHiles** [comment]
@the-meedu-app when I add the app id to the manifest I get the following error (which is what led me to believe I don't need to add the app ID):

```console
Launching lib\main.dart on Pixel 4 XL in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> org.xml.sax.SAXParseException; systemId: file:/C:/Users/haden/Repos/thepondapp/android/app/src/main/AndroidManifest.xml; lineNumber: 38; columnNumber: 34; The prefix "tools" for attribute "tools:replace" associated with an element type "meta-data" is not bound.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

Curious as to why nobody else has experienced this, maybe I missed something idk 🤔

**Comment by HadenHiles** [comment]
Oops 🤦 here is without the attempt to do tools:replace...

```console
Launching lib\main.dart on Pixel 4 XL in debug mode...
C:\Users\haden\Repos\thepondapp\android\app\src\debug\AndroidManifest.xml:37:9-48 Error:
	Attribute meta-data#com.facebook.sdk.ApplicationId@value value=(@string/facebook_app_id) from AndroidManifest.xml:37:9-48
	is also present at [com.firebaseui:firebase-ui-auth:6.2.0] AndroidManifest.xml:21:13-60 value=(@string/facebook_application_id).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#com.facebook.sdk.ApplicationId@value value=(@string/facebook_app_id) from AndroidManifest.xml:37:9-48
  	is also present at [com.firebaseui:firebase-ui-auth:6.2.0] AndroidManifest.xml:21:13-60 value=(@string/facebook_application_id).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by HadenHiles** [comment]
UPDATE: after removing `implementation 'com.firebaseui:firebase-ui-auth:6.2.0'` from my build.gradle and adding `<string name="app_name">thepondapp</string>` to my strings.xml I got it to work. Thank you for your help!
